### ISSUE TITLE
SVG scrambled

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-mpdf#4]
WP 4.4.1, PB 3.1.2, PBT 2.1.2, PmPDF 1.0.1

SVG in Webpage:
![before](https://cloud.githubusercontent.com/assets/360534/12714744/c2a0e58a-c8d6-11e5-8a74-eccc84fbe4ec.png)
SVG in mPDF Export
![after](https://cloud.githubusercontent.com/assets/360534/12714760/cfa40a50-c8d6-11e5-81c5-61d87ee060d5.png)

**Comment by bdolor** [comment]
mPDF partially supports SVG images: http://mpdf1.com/manual/index.php?tid=245 — In order to treat this as a problem with the plugin's use of mPDF as opposed to a limitation of the mPDF class, I would need assurance that this is indeed an issue that is specific to the plugin. Please re-open if that is the case.
